/**
 * Case-detail chat — streaming + AI-suggested prompts.
 *
 * The "Asistente Legal IA" panel inside a case used to fire one synchronous
 * /query call. We replace that with:
 *
 *   POST /cases/:id/chat                 (SSE) streaming Claude reply
 *                                        with case context auto-injected.
 *   GET  /cases/:id/chat/suggestions     6 case-specific quick-prompts
 *                                        generated by the AI from the
 *                                        actual case material.
 *
 * Lives next to (not replacing) src/routes/query.ts so the older RAG
 * pipeline keeps working.
 */
import { FastifyInstance } from 'fastify';
import { z } from 'zod';
import { prisma } from '../lib/prisma.js';
import { getAiClient } from '../lib/ai-client.js';
import { getUserCountryContext } from '../lib/country-context.js';

interface ChatTurn { role: 'user' | 'assistant'; content: string }

const TONE_HINTS: Record<string, string> = {
  formal:    'Tono forense formal, español jurídico de altura, trato protocolar.',
  practico:  'Tono práctico y directo, oraciones cortas, accionable.',
  didactico: 'Tono didáctico para explicar al cliente: claro, sin jerga sin definir.',
};

const LENGTH_HINTS: Record<string, string> = {
  corta:    'Respuesta concisa: máximo 4-6 frases.',
  estandar: 'Respuesta estándar: 1-2 párrafos.',
  detallada:'Respuesta detallada: 3-5 párrafos con bullets si aporta.',
};

export async function caseChatRoutes(fastify: FastifyInstance) {
  /**
   * GET /cases/:id/chat/suggestions
   * Pide al modelo 6 quick-prompts pegados a este caso particular.
   */
  fastify.get<{ Params: { id: string } }>(
    '/cases/:id/chat/suggestions',
    { onRequest: [fastify.authenticate] },
    async (request, reply) => {
      const userId = (request.user as any).id;
      const c = await prisma.case.findFirst({
        where: { id: request.params.id, userId },
        include: {
          documents: { take: 5, orderBy: { createdAt: 'desc' },
            select: { title: true, content: true } },
          events: { take: 5, orderBy: { startTime: 'desc' },
            select: { title: true, type: true, startTime: true } },
        },
      });
      if (!c) return reply.code(404).send({ error: 'CASE_NOT_FOUND' });

      const country = await getUserCountryContext(userId);
      const docExcerpts = c.documents
        .map((d, i) => `[Doc ${i + 1}] ${d.title}: ${d.content.replace(/\s+/g, ' ').slice(0, 400)}`)
        .join('\n');
      const evList = c.events
        .map((e) => `${new Date(e.startTime).toISOString().slice(0, 10)} ${e.type}: ${e.title}`)
        .join('\n');

      const systemPrompt =
        `Eres un abogado(a) senior en ${country.nameEs}. Te dan información de un caso real ` +
        'y debes proponer 6 PREGUNTAS o ACCIONES rápidas, concretas y útiles que un abogado le ' +
        'haría a su asistente IA en ese caso. NO repitas las que están en otras categorías. ' +
        'NO inventes datos. Si no hay material suficiente, propones preguntas exploratorias.\n\n' +
        'Devuelve SOLO un JSON minificado:\n' +
        '{"suggestions":[{"icon":"📄","label":"…","prompt":"…","category":"analisis"|"redaccion"|"investigacion"|"estrategia"|"riesgo"|"cliente"}]}\n' +
        'Reglas: label máx 30 chars; prompt máx 160 chars, en 1ª persona del usuario ' +
        '("Resume los hechos clave..."); icon es UN emoji único.';

      const userPrompt = [
        `=== CASO ===`,
        `Título: ${c.title}`,
        c.caseNumber ? `Causa: ${c.caseNumber}` : '',
        c.description ? `Descripción: ${c.description}` : '',
        c.clientName ? `Cliente: ${c.clientName}` : '',
        '',
        '=== DOCUMENTOS ===',
        docExcerpts || '(ninguno)',
        '',
        '=== EVENTOS ===',
        evList || '(ninguno)',
      ].filter(Boolean).join('\n');

      // Sugerencias genéricas para que la UI NUNCA aparezca vacía si la IA falla.
      // Categorías: análisis, redacción, investigación, estrategia, riesgo, cliente.
      const fallbackSuggestions = [
        { icon: '📋', label: 'Resumen ejecutivo',    prompt: 'Resume los hechos clave del caso en orden cronológico, identificando partes, pretensiones y etapa procesal.', category: 'analisis' as const },
        { icon: '⚖️', label: 'Normativa aplicable',  prompt: 'Identifica las normas aplicables del corpus legal a este caso y explica por qué cada una aplica.', category: 'investigacion' as const },
        { icon: '🎯', label: 'Estrategia procesal',  prompt: 'Propón una estrategia procesal: pretensiones, pruebas a aportar y posibles incidentes.', category: 'estrategia' as const },
        { icon: '⚠️', label: 'Riesgos del caso',     prompt: 'Identifica los principales riesgos (plazos, prescripción, contradicciones probatorias) y cómo mitigarlos.', category: 'riesgo' as const },
        { icon: '📝', label: 'Borrador de escrito',  prompt: 'Redacta un borrador del próximo escrito que conviene presentar dado el estado actual del caso.', category: 'redaccion' as const },
        { icon: '💬', label: 'Explicar al cliente',  prompt: 'Explica el estado del caso al cliente en lenguaje claro, sin tecnicismos, en 1 párrafo.', category: 'cliente' as const },
      ];

      try {
        const aiClient = await getAiClient();
        const completion = await aiClient.chat.completions.create({
          messages: [
            { role: 'system', content: systemPrompt },
            { role: 'user', content: userPrompt },
          ],
          temperature: 0.4,
          max_tokens: 800,
        });
        const raw = (completion.choices?.[0]?.message?.content || '').trim();

        // Capa 1: parse directo (luego de quitar fences)
        const fenced = raw.replace(/^```(?:json)?\s*/i, '').replace(/\s*```\s*$/i, '').trim();
        let parsed: any = null;
        try { parsed = JSON.parse(fenced); } catch {
          // Capa 2: primer objeto JSON balanceado
          const start = fenced.indexOf('{');
          if (start >= 0) {
            let depth = 0, inString = false, escape = false;
            for (let i = start; i < fenced.length; i++) {
              const ch = fenced[i];
              if (escape) { escape = false; continue; }
              if (ch === '\\') { escape = true; continue; }
              if (ch === '"') { inString = !inString; continue; }
              if (inString) continue;
              if (ch === '{') depth++;
              else if (ch === '}') {
                depth--;
                if (depth === 0) {
                  try { parsed = JSON.parse(fenced.slice(start, i + 1)); } catch {}
                  break;
                }
              }
            }
          }
        }

        const VALID_CATS = ['analisis','redaccion','investigacion','estrategia','riesgo','cliente'] as const;
        const rawList = parsed && Array.isArray(parsed.suggestions) ? parsed.suggestions : [];
        const suggestions = rawList.slice(0, 6).map((s: any) => ({
          icon: typeof s?.icon === 'string' && s.icon.length > 0 ? s.icon.slice(0, 4) : '✨',
          label: String(s?.label ?? '').slice(0, 60),
          prompt: String(s?.prompt ?? '').slice(0, 240),
          category: VALID_CATS.includes(s?.category) ? s.category : 'analisis',
        })).filter((s: any) => s.label && s.prompt);

        // Si la IA devolvió 0-2 sugerencias, completamos con las genéricas.
        if (suggestions.length < 3) {
          const need = 6 - suggestions.length;
          const seen = new Set(suggestions.map((s: any) => s.label));
          for (const f of fallbackSuggestions) {
            if (seen.has(f.label)) continue;
            suggestions.push(f);
            if (suggestions.length >= 6) break;
            if (suggestions.length - rawList.length >= need) break;
          }
        }

        return { suggestions, country: country.code };
      } catch (err: any) {
        request.log.error({ err: err?.message }, 'chat-suggestions falló — devolviendo fallback');
        // Failsafe: que la UI nunca se vea vacía, incluso si la IA cae.
        return { suggestions: fallbackSuggestions, country: country.code, fallback: true };
      }
    },
  );

  /**
   * POST /cases/:id/chat (SSE)
   * Body: { message, history?: [{role,content}], tone?, length?, language? }
   */
  fastify.post<{ Params: { id: string }; Body: any }>(
    '/cases/:id/chat',
    { onRequest: [fastify.authenticate] },
    async (request, reply) => {
      const userId = (request.user as any).id;
      const body = z.object({
        message: z.string().min(1).max(4000),
        history: z.array(z.object({
          role: z.enum(['user', 'assistant']),
          content: z.string(),
        })).max(20).optional(),
        tone: z.enum(['formal', 'practico', 'didactico']).default('formal'),
        length: z.enum(['corta', 'estandar', 'detallada']).default('estandar'),
        language: z.enum(['es', 'en']).default('es'),
      }).parse(request.body);

      const c = await prisma.case.findFirst({
        where: { id: request.params.id, userId },
        include: {
          documents: {
            take: 6, orderBy: { createdAt: 'desc' },
            select: { id: true, title: true, content: true },
          },
          events: {
            take: 8, orderBy: { startTime: 'asc' },
            select: { title: true, type: true, startTime: true },
          },
        },
      });
      if (!c) return reply.code(404).send({ error: 'CASE_NOT_FOUND' });

      const country = await getUserCountryContext(userId);

      const docContext = c.documents
        .map((d, i) => `[Documento ${i + 1}] ${d.title}\n${d.content.replace(/\s+/g, ' ').slice(0, 1000)}`)
        .join('\n\n');
      const timeline = c.events
        .map((e) => `- ${new Date(e.startTime).toISOString().slice(0, 10)} ${e.type}: ${e.title}`)
        .join('\n');

      const systemPrompt = [
        `Eres un(a) abogado(a) senior con 25 años de experiencia, ejerciendo en ${country.nameEs}.`,
        `Sistema legal: ${country.legalSystem === 'common_law' ? 'common law' : 'civil law'}. Idioma: ${body.language === 'en' ? 'inglés' : 'español'} jurídico.`,
        TONE_HINTS[body.tone],
        LENGTH_HINTS[body.length],
        '',
        'REGLAS:',
        '1) Cita artículos y normas con número exacto. Si no estás 100% seguro, escribe "[CITA POR VERIFICAR]" en lugar de inventar.',
        '2) Apoya tus respuestas en el material del expediente que se te entrega abajo. Si la respuesta no está en el material, dilo.',
        '3) Estructura con encabezados markdown (##), negritas y listas cuando ayuden.',
        '4) Cuando sugieras pasos, sé específico: documento, plazo, autoridad.',
        '5) No inventes jurisprudencia ni cita doctrinaria. Sin "NN" ni placeholders genéricos.',
        '',
        '=== CASO ===',
        `Título: ${c.title}`,
        c.caseNumber ? `Causa: ${c.caseNumber}` : '',
        c.clientName ? `Cliente: ${c.clientName}` : '',
        c.description ? `Descripción: ${c.description}` : '',
        '',
        '=== EXPEDIENTE (extractos de documentos) ===',
        docContext || '(sin documentos cargados)',
        '',
        '=== CRONOLOGÍA ===',
        timeline || '(sin eventos)',
      ].filter(Boolean).join('\n');

      reply
        .raw.setHeader('Content-Type', 'text/event-stream')
        .setHeader('Cache-Control', 'no-cache, no-transform')
        .setHeader('Connection', 'keep-alive')
        .setHeader('X-Accel-Buffering', 'no');
      reply.raw.flushHeaders?.();
      const send = (event: string, data: any) => {
        reply.raw.write(`event: ${event}\n`);
        reply.raw.write(`data: ${JSON.stringify(data)}\n\n`);
      };

      try {
        const aiClient = await getAiClient();
        const messages: ChatTurn[] = [
          ...(body.history ?? []).slice(-12),
          { role: 'user', content: body.message },
        ];
        send('start', { provider: aiClient.provider, model: aiClient.model });

        if (aiClient.provider === 'openai') {
          const stream: any = await aiClient.chat.completions.create({
            messages: [
              { role: 'system', content: systemPrompt },
              ...messages,
            ] as any,
            temperature: 0.3,
            max_tokens: 2400,
            stream: true,
          });
          for await (const chunk of stream) {
            const delta = chunk?.choices?.[0]?.delta?.content;
            if (delta) send('chunk', { content: delta });
          }
        } else {
          const completion = await aiClient.chat.completions.create({
            messages: [
              { role: 'system', content: systemPrompt },
              ...messages,
            ] as any,
            temperature: 0.3,
            max_tokens: 2400,
          });
          const text = completion.choices?.[0]?.message?.content ?? '';
          // Trocea por palabras para que la UI sienta streaming.
          for (const w of text.split(/(\s+)/)) {
            if (w) send('chunk', { content: w });
          }
        }
        send('done', { ok: true });
      } catch (err: any) {
        request.log.error({ err }, 'case-chat failed');
        send('error', { message: err?.message ?? 'AI error' });
      } finally {
        reply.raw.end();
      }
      return reply;
    },
  );
}
