/**
 * Demo page for document summarization streaming
 * Path: /summarization-demo
 */

import React from 'react';
import SummarizationStreamingExample from '@/components/SummarizationStreamingExample';

export const metadata = {
  title: 'Document Summarization Demo | Legal RAG System',
  description: 'Real-time AI-powered document summarization using Server-Sent Events',
};

/**
 * Summarization demo page component
 * Showcases the useSummarizationStreaming hook functionality
 */
export default function SummarizationDemoPage() {
  return (
    <main className="min-h-screen bg-gradient-to-br from-gray-50 to-gray-100">
      <div className="container mx-auto py-8 px-4">
        <SummarizationStreamingExample />

        {/* Additional information section */}
        <div className="max-w-4xl mx-auto mt-12 space-y-6">
          <div className="bg-white rounded-lg shadow-md p-6">
            <h2 className="text-2xl font-bold text-gray-900 mb-4">
              How It Works
            </h2>
            <div className="space-y-3 text-gray-700">
              <p>
                This demonstration uses Server-Sent Events (SSE) to stream document summaries
                in real-time as they are generated by our AI system.
              </p>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>
                  <strong>Real-time streaming:</strong> Summary content appears as it's generated,
                  providing instant feedback
                </li>
                <li>
                  <strong>Three detail levels:</strong> Choose between brief, standard, or detailed
                  summaries based on your needs
                </li>
                <li>
                  <strong>Multilingual support:</strong> Generate summaries in Spanish, English,
                  French, or German
                </li>
                <li>
                  <strong>Quality metrics:</strong> View word count, compression ratio, and
                  processing time
                </li>
                <li>
                  <strong>Cancellable:</strong> Stop streaming at any time if you need to change
                  parameters
                </li>
              </ul>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
              <h3 className="font-semibold text-blue-900 mb-2">Brief Summary</h3>
              <p className="text-sm text-blue-800">
                1-2 paragraphs covering main points. Perfect for quick overview.
              </p>
              <p className="text-xs text-blue-600 mt-2">Avg: 100-150 words</p>
            </div>

            <div className="bg-green-50 border border-green-200 rounded-lg p-4">
              <h3 className="font-semibold text-green-900 mb-2">Standard Summary</h3>
              <p className="text-sm text-green-800">
                3-5 paragraphs with key details. Balanced coverage.
              </p>
              <p className="text-xs text-green-600 mt-2">Avg: 250-400 words</p>
            </div>

            <div className="bg-purple-50 border border-purple-200 rounded-lg p-4">
              <h3 className="font-semibold text-purple-900 mb-2">Detailed Summary</h3>
              <p className="text-sm text-purple-800">
                Comprehensive analysis with examples and context.
              </p>
              <p className="text-xs text-purple-600 mt-2">Avg: 500-800 words</p>
            </div>
          </div>

          <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-4">
            <div className="flex items-start gap-3">
              <svg
                className="w-6 h-6 text-yellow-600 mt-0.5 flex-shrink-0"
                fill="currentColor"
                viewBox="0 0 20 20"
              >
                <path
                  fillRule="evenodd"
                  d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z"
                  clipRule="evenodd"
                />
              </svg>
              <div>
                <h3 className="font-semibold text-yellow-900 mb-1">Test Document IDs</h3>
                <p className="text-sm text-yellow-800">
                  Use these sample document IDs to test the summarization feature:
                </p>
                <ul className="list-disc list-inside mt-2 space-y-1 text-sm text-yellow-700 ml-4">
                  <li><code className="bg-yellow-100 px-1 rounded">doc_sample_001</code> - Civil Code Article</li>
                  <li><code className="bg-yellow-100 px-1 rounded">doc_sample_002</code> - Contract Law Case</li>
                  <li><code className="bg-yellow-100 px-1 rounded">doc_sample_003</code> - Constitutional Amendment</li>
                </ul>
              </div>
            </div>
          </div>

          <div className="bg-white rounded-lg shadow-md p-6">
            <h2 className="text-2xl font-bold text-gray-900 mb-4">
              Technical Details
            </h2>
            <div className="space-y-3 text-gray-700 text-sm">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <h4 className="font-semibold text-gray-900 mb-2">Frontend</h4>
                  <ul className="space-y-1 text-gray-600">
                    <li>React Hooks (useState, useCallback, useRef)</li>
                    <li>EventSource API for SSE</li>
                    <li>TypeScript for type safety</li>
                    <li>Automatic reconnection handling</li>
                    <li>Memory-efficient streaming</li>
                  </ul>
                </div>
                <div>
                  <h4 className="font-semibold text-gray-900 mb-2">Backend</h4>
                  <ul className="space-y-1 text-gray-600">
                    <li>Server-Sent Events (SSE) protocol</li>
                    <li>OpenAI GPT-4 for summarization</li>
                    <li>Token streaming for real-time updates</li>
                    <li>Quality metrics calculation</li>
                    <li>Caching for performance</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>

          <div className="bg-gray-800 text-white rounded-lg p-6">
            <h3 className="text-xl font-bold mb-3">Code Example</h3>
            <pre className="bg-gray-900 p-4 rounded overflow-x-auto text-sm">
              <code>{`import { useSummarizationStreaming } from '@/hooks/useSummarizationStreaming';

function MyComponent() {
  const { content, status, startStreaming } = useSummarizationStreaming();

  return (
    <div>
      <button onClick={() => startStreaming({
        documentId: 'doc_123',
        level: 'standard',
        language: 'es'
      })}>
        Summarize
      </button>
      {status === 'streaming' && <p>Loading...</p>}
      <div>{content}</div>
    </div>
  );
}`}</code>
            </pre>
          </div>

          <div className="bg-white rounded-lg shadow-md p-6">
            <h2 className="text-2xl font-bold text-gray-900 mb-4">
              API Documentation
            </h2>
            <div className="overflow-x-auto">
              <table className="min-w-full divide-y divide-gray-200">
                <thead className="bg-gray-50">
                  <tr>
                    <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Endpoint
                    </th>
                    <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Method
                    </th>
                    <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Response Type
                    </th>
                  </tr>
                </thead>
                <tbody className="bg-white divide-y divide-gray-200">
                  <tr>
                    <td className="px-4 py-3 text-sm text-gray-900">
                      <code>/api/v1/summarization/stream</code>
                    </td>
                    <td className="px-4 py-3 text-sm text-gray-900">GET</td>
                    <td className="px-4 py-3 text-sm text-gray-900">
                      <code>text/event-stream</code>
                    </td>
                  </tr>
                  <tr>
                    <td className="px-4 py-3 text-sm text-gray-900">
                      <code>/api/v1/summarization</code>
                    </td>
                    <td className="px-4 py-3 text-sm text-gray-900">POST</td>
                    <td className="px-4 py-3 text-sm text-gray-900">
                      <code>application/json</code>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </main>
  );
}
